remote_theme: pages-themes/architect@v0.2.0

plugins:
- jekyll-remote-theme

title: "TgCore • Fluent DSL for APIs & AI"
description: "Designed for complex systems. Made simple. A fluent DSL for building Telegram bots, APIs, and AI workflows."
